root: true

extends:
    - plugin:react/recommended
    - plugin:@typescript-eslint/recommended

parser: "@typescript-eslint/parser"

parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 2020
    sourceType: module

plugins:
    - "@typescript-eslint"
    - react

settings:
    react:
        version: detect

env:
    browser: true
    node: true
    es6: true

globals:
    React: writable

ignorePatterns:
    - src/components/**/*.d.ts
    - .generated/**/*
    - "*.scss"
    - "**/*.js"

rules:
    "@typescript-eslint/no-explicit-any": off
    "@typescript-eslint/no-unused-vars":
        - error
        - argsIgnorePattern: ^_
          varsIgnorePattern: ^_
    jsx-quotes:
        - error
        - prefer-double
    no-console:
        - error
        - allow:
              - warn
              - error
              - info
    no-unused-vars: off

    # Prevent missing props validation in a React component definition
    react/prop-types: off

    # Needed for NextJS in order to use JSX without React import
    react/react-in-jsx-scope: off
